name: Create Archive
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "NoozSBC"
        git config --global user.email "zhengm58@gmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'CalamityMaskupPack.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig hash.txt'
    - name: Generate hashsum
      run: |
        sha1sum CalamityMaskupPack.zip | cut -d " " -f 1 | tee hash.txt
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "Update pack"
        git push --force
